name: upstream

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * *'

  watch:
    types: [started]

jobs:
  upstream:
    runs-on: ubuntu-latest
    if: github.repository == 'idrblab/socube-apidoc'
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - uses: actions/checkout@v3

      - name: Sync with upstream
        continue-on-error: false
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: GCS-ZHN/socube-apidoc
          upstream_sync_branch: ${{ matrix.branch }}
          target_sync_branch: ${{ matrix.branch }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs'
